---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/mynewapp:appimage
   deploy:
     replicas: 2
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
